server:
  port: 8080

spring:
  application:
    name: 'biblioteca'

  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      schema: biblioteca
    url: jdbc:postgresql://localhost:5432/dbtestes
    username: postgres
    password: postgres

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: biblioteca

  flyway:
    baseline-on-migrate: true
    schemas: biblioteca

biblioteca:
  mail:
    username: library.ifsp@gmail.com
    password: 
